name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        name: install node
        with:
          node-version: 14
      - name: Install packages
        run: yarn install
      - name: Run tests
        run: yarn test
      - name: Build production bundle
        if: ${{ success() }}
        run: yarn build
      - name: Deploy to GitHub Pages
        if: ${{ success() }}
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
